version: '3'

services:
  elastic-search:
    build: .
    container_name: elastic-search
    environment:
      - discovery.type=single-node
    networks:
      - elastic
    ports:
      - "9200:9200"
      - "9300:9300"

    volumes:
      - base-station-elastic-data:/output

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.21
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic-search:9200
    networks:
      - elastic
    ports:
      - "5601:5601"

networks:
  data-acquisition:
    external: true
  elastic:
    external: true
      

volumes:
  base-station-elastic-data:
    external: true
