version: '3'

services:
  base-central-station:
    image: base-central-station
    container_name: base-central-station
    environment:

    networks:
      - elastic
      - data-acquisition

    volumes:
      - base-station-elastic-data:/output

networks:
  data-acquisition:
    external: true
  elastic:
    external: true

volumes:
  base-station-elastic-data:
    external: true
